namespace bikabika
{
    runtimeclass BikaHttp
    {
        BikaHttp();
        String Auth;
        Windows.Foundation.IAsyncOperation<String> Login(String account, String password);
        Windows.Foundation.IAsyncOperation<String> PersonInfo();
    }
}
