import "ClassBlockViewModel.idl";
namespace bikabika
{
    [default_interface]
    runtimeclass ClassificationPage : Windows.UI.Xaml.Controls.Page
    {
        ClassificationPage();
        ClassBlockViewModel ClassBlockView{ get; };
    }
}
