namespace bikabika
{
    runtimeclass ClassBlock : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        ClassBlock(String className, String classPic);
        String ClassName{ get; };
        String ClassPic{ get; };
    }
}