namespace bikabika
{
    runtimeclass ComicBlock : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        ComicBlock(Windows.Data.Json.JsonObject json);
        String ID;
        String Title;
        String Author;
        Int32 TotalViews;
        Int32 TotalLikes;
        Int32 PageCount;
        Int32 EpsCount;
        Boolean Finished;
        Windows.Data.Json.JsonArray Categories;
        Windows.UI.Xaml.Media.Imaging.BitmapImage Thumb;
        Int32 LikesCount;
    }
}