import "ComicBlock.idl";
namespace bikabika
{

    runtimeclass ComicsPage : Windows.UI.Xaml.Controls.Page
    {
        ComicsPage();
        Windows.Foundation.Collections.IObservableVector<bikabika.ComicBlock>  ComicBlocks{ get; };
       
    }
}
