namespace bikabika
{
    enum SearchSortMode
    {
        UA = 0,
        DD = 1,
        DA = 2,
        LD = 3,
        VD = 4
    };
    enum ComicsType
    {
        // 分区
        COMIC = 0,
        // 搜索
        SEARCH = 1,
        // 历史记录
        HISTORY = 2,
        // 喜爱的作品
        FACOURITE = 3
    };
    runtimeclass ComicArgs
    {
        ComicArgs();
        ComicsType ComicType;
        String Content;
        SearchSortMode SortMode;
        String SortModeString{ get; };
        Boolean IsAnime;
    }
}