namespace bikabika
{
	runtimeclass FileCheckTool
	{
		FileCheckTool();
		Windows.Foundation.IAsyncOperation<Boolean> CheckFileAccount();
		Windows.Foundation.IAsyncOperation<Boolean> CheckFileUser();
		Windows.Foundation.IAsyncOperation<Windows.Data.Json.JsonObject> GetAccount();
	}
}