import "TagBlock.idl";
import "CreaterBlock.idl";
import "EpisodeBlock.idl";
namespace bikabika
{
    [default_interface]
    runtimeclass InfoPage : Windows.UI.Xaml.Controls.Page
    {
        InfoPage();
        Windows.Foundation.Collections.IObservableVector<bikabika.TagBlock> Tags{ get; };
        Windows.Foundation.Collections.IObservableVector<bikabika.EpisodeBlock> Episodes{ get; };
        Windows.UI.Xaml.Controls.Border CreaterBorder{ get; };
    }
}
