import "CreaterBlock.idl";
import "TagBlock.idl";
namespace bikabika
{
    runtimeclass InfoBlock : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        InfoBlock(Windows.Data.Json.JsonObject json);
        String ID;
        String Title{ get; };
        bikabika.CreaterBlock Creater;
        String Description;
        Windows.UI.Xaml.Media.Imaging.BitmapImage Thumb;
        String Author{ get; };
        String ChineseTeam;
        Windows.Foundation.Collections.IObservableVector<bikabika.TagBlock> Categories;
        String CategoriesString;
        Windows.Foundation.Collections.IObservableVector<bikabika.TagBlock> Tags;
        String TagsString;
        Int32 PagesCount;
        Int32 EpsCount;
        Windows.UI.Xaml.Visibility Finished;
        String UpdatedAt;
        String CreatedAt;
        Boolean AllowDownload;
        Boolean AllowComment;
        Int32 TotalLikes;
        Int32 TotalViews;
        Int32 ViewsCount;
        Int32 LikesCount;
        Boolean IsFavourite;
        Boolean IsLiked;
        Int32 CommentsCount;
    }
}