import "TagBlock.idl";
import "CreaterBlock.idl";
namespace bikabika
{
    [default_interface]
    runtimeclass InfoPage : Windows.UI.Xaml.Controls.Page
    {
        InfoPage();
        Windows.Foundation.Collections.IObservableVector<bikabika.TagBlock> Tags{ get; };
    }
}
