
namespace bikabika
{

    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();
        Int32 MyProperty;
        Windows.UI.Xaml.Controls.CheckBox UseCustomColorCheckBox{ get; };
        Windows.UI.Xaml.Controls.TextBlock UserName{ get; };
    }
}
