namespace bikabika{

	runtimeclass PageNumBox : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        PageNumBox(Int32 pageIndex,Int32 pages, String title);
        Int32 PageIndex;
        Int32 Pages;
        String Title;
    }
}