import "Utils/Blocks/UserViewModel.idl";
namespace bikabika
{
    [default_interface]
    runtimeclass UserPage : Windows.UI.Xaml.Controls.Page
    {
        UserPage();
        UserViewModel MainUserViewModel{ get; };
    }
}
