import "Utils/Blocks/UserViewModel.idl";
import "Utils/Blocks/ComicBlock.idl";
namespace bikabika
{
    [default_interface]
    runtimeclass UserPage : Windows.UI.Xaml.Controls.Page
    {
        UserPage();
        UserViewModel MainUserViewModel{ get; };
        Windows.Foundation.Collections.IObservableVector<bikabika.ComicBlock>  FavComicBlocks{ get; };
        Windows.Foundation.Collections.IObservableVector<bikabika.ComicBlock>  LookComicBlocks{ get; };
    }
}
