namespace bikabika
{
    [default_interface]
    runtimeclass ClassificationPage : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        ClassificationPage();
        Windows.Foundation.Collections.IObservableVector<BikaClient.Blocks.CategoriesBlock> Categories{ get; };
    }
}
