import "CommentView.idl";
namespace bikabika
{
    [default_interface]
    runtimeclass InfoPage : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        InfoPage();
        bikabika.CommentView GetCommentView{ get; };
        BikaClient.Blocks.BookBlock Book{ get; };
        Windows.UI.Xaml.Controls.Border DesBorder{ get; };
    }
}
