namespace bikabika
{
    [default_interface]
    runtimeclass SettingsPage : Windows.UI.Xaml.Controls.Page
    {
        SettingsPage();
        Windows.UI.Xaml.Controls.Grid BackGrid{ get; };
    }
}
