namespace bikabika
{
    [default_interface]
    runtimeclass SettingsPage : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        SettingsPage();
        Double SettingWidth{ get; };
        Double SettingConentWidth{ get; };
    }
}
