namespace bikabika
{
    enum ComicsType
    {
        // 分区
        COMIC = 0,
        // 搜索
        SEARCH = 1,
        // 历史记录
        HISTORY = 2,
        // 喜爱的作品
        FACOURITE = 3,
        // 最近更新
	    RECENTLY_UPDATE = 4,
	    // 随机本子
	    RANDOM = 5,
    };
    runtimeclass ComicArgs
    {
        ComicArgs();
        ComicArgs(ComicsType comicType, String title, BikaClient.Utils.BikaSort sortMode);
        ComicsType ComicType;
        String Title;
        BikaClient.Utils.BikaSort SortMode;
        String SortModeString{ get; };
        Boolean IsAnime;
    }
}