namespace bikabika
{
    runtimeclass BikaHttp
    {
        BikaHttp();

        Windows.Foundation.IAsyncOperation<String> Login(String account, String password);
        Windows.Foundation.IAsyncOperation<String> PersonInfo();
        Windows.Foundation.IAsyncOperation<String> Categories();
        Windows.Foundation.IAsyncOperation<String> Keywords();
        Windows.Foundation.IAsyncOperation<String>  Comics(Int32 page, String title, String sort);
        Windows.Foundation.IAsyncOperation<String>  BookInfo(String bookId);
        Windows.Foundation.IAsyncOperation<String>  Episodes(String bookId, Int32 page);
        Windows.Foundation.IAsyncOperation<String>  Picture(String bookId, Int32 epsId, Int32 page);
        Windows.Foundation.IAsyncOperation<String>  PersonFavourite(String sort, Int32 page);
        Windows.Foundation.IAsyncOperation<String>  PersonComment(Int32 page);
        Windows.Foundation.IAsyncOperation<String> Search(String keywords, String sort, Windows.Data.Json.JsonArray categories, Int32 page);
        Windows.Foundation.IAsyncOperation<String> Favourite(String bookId);
        Windows.Foundation.IAsyncOperation<String> Like(String bookId);
        

    }
}
