import "Utils/Blocks/ClassBlock.idl";
namespace bikabika
{
    runtimeclass ClassBlockViewModel
    {
        ClassBlockViewModel();
        bikabika.ClassBlock DefaultClassBlock{ get; };
        Windows.Foundation.Collections.IObservableVector<bikabika.ClassBlock> ClassBlocks{ get; };
    }
}