import "Utils/Blocks/CreaterBlock.idl";
namespace bikabika
{
    runtimeclass CommentBlock : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        CommentBlock(Windows.Data.Json.JsonObject json);
        String Content;
        Boolean IsTop;
        Windows.UI.Xaml.Visibility Top;
        Windows.UI.Xaml.Visibility Hide;
        String CreatedAt;
        Int32 LikesCount;
        Int32 CommentsCount;
        bikabika.CreaterBlock Creater;
        Windows.UI.Xaml.Visibility IsLiked;
        Windows.Data.Json.JsonObject GetJsonObject{ get; };
    }
}