namespace bikabika
{
	runtimeclass KeywordsBox
	{
		KeywordsBox(String keywords, String messages,String keywordType,Windows.UI.Xaml.Media.Imaging.BitmapImage keywordIcon);
		String GetKeywords{ get; };
		String GetMessages{ get; };
		String GetKeywordType{ get; };
		Windows.UI.Xaml.Media.Imaging.BitmapImage GetKeywordIcon{ get; };
	}
}