namespace bikabika
{
    runtimeclass User : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        User(String name,String level);
        String Name;
        String Level;
        Windows.UI.Xaml.Media.Imaging.BitmapImage Img;
        String ImageSource;
        String Slogan;
        Int32 Exp;
        Int32 Percent;
        String Title;
        String LevelExp;
    }
}