namespace bikabika
{
    runtimeclass User : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        User(String name,String level);
        String ID;
        String Name;
        String CreatedAt;
        String Birthday;
        String Email;
        String Level;
        String LevelString;
        Boolean  IsPunched;
        Boolean  Verified;
        String  IsPunchedString;
        String  VerifiedString;
        String  Gender;
        Windows.UI.Xaml.Media.Imaging.BitmapImage Img;
        String ImageSource;
        String Slogan;
        Int32 Exp;
        Int32 Percent;
        String Title;
        String LevelExp;
        void Clear();
    }
}