import "Utils/Blocks/ClassBlockViewModel.idl";
import "Utils/API/BikaHttp.idl";
namespace bikabika
{
    [default_interface]
    runtimeclass ClassificationPage : Windows.UI.Xaml.Controls.Page
    {
        ClassificationPage();
        ClassBlockViewModel ClassBlockView{ get; };
        BikaHttp BikaHttpAPI{ get; };
    }
}
