import "Utils/Blocks/ComicBlock.idl";
import "Utils/Blocks/PageNumBox.idl";
namespace bikabika
{

    runtimeclass ComicsPage : Windows.UI.Xaml.Controls.Page
    {
        ComicsPage();
        Windows.Foundation.Collections.IObservableVector<bikabika.ComicBlock>  ComicBlocks{ get; };
        Windows.Foundation.Collections.IObservableVector<String>  TypeBlocks{ get; };
        bikabika.PageNumBox MyPageNumBox{ get; };

    }
}
