import "Utils/Blocks/TagBlock.idl";
import "Utils/Blocks/CommetsViewModel.idl";
namespace bikabika
{
    runtimeclass InfoPage : Windows.UI.Xaml.Controls.Page
    {
        InfoPage();
        Windows.Foundation.Collections.IObservableVector<bikabika.TagBlock> Tags{ get; };
        bikabika.CommetsViewModel CommentBlocks{ get; };
        Windows.UI.Xaml.Controls.Border CreaterBorder{ get; };
    }
}
