import "Utils/Blocks/UserViewModel.idl";
namespace bikabika
{

    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();
        UserViewModel MainUserViewModel{ get; };
        String PicPath{ get; };
        static MainPage Current{ get; };
        void CreateNewTab(Windows.UI.Xaml.Controls.Frame frame, String title, Microsoft.UI.Xaml.Controls.SymbolIconSource symbol);
        void ContentDialogShow(String mode, String message);
        Windows.Foundation.IAsyncAction SetPerson();
        void LogOut();
        void ChangeSignature();
        void ChangePassword();
    }
}
