import "Utils/Blocks/PicturesBlock.idl";
namespace bikabika
{
	[default_interface]
	runtimeclass PicPage : Windows.UI.Xaml.Controls.Page
	{
		PicPage();
		Windows.Foundation.Collections.IObservableVector<bikabika.PicturesBlock> PicturesBlocks{ get; };
	}
}
